spring.application.name=empresa-crud

# PostgreSQL - Supabase (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.yuncybiaaiabteykcqig
spring.datasource.password=xbRDUJjeO5zb3viR

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true